packages:
  prometheus-stack:
    grafana:
      enabled: false
      image:
        registry:
        repository:
        tag:
      ingress:
        host:
      web:
        externalUrl:
      auth:
        oidc:
          enabled: false
          providers:
            generic: {}
            microsoft: {}
      dataSources:
        - name: Loki
          type: loki
          url: http://loki-gateway.dev-genx-infra-loki.svc.cluster.local
          tenantName: loki
